name: Java CI with Maven and SemVer Release

on:
  push:
    branches: [ "master", "main" ] # main 브랜치 호환 추가
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Bump version and push tag
      id: tag_version
      if: github.event_name == 'push'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        release_branches: master,main # main 브랜치 호환 추가

    - name: Update Maven Version
      if: github.event_name == 'push' && steps.tag_version.outputs.new_version
      run: |
        mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_version }} -DgenerateBackupPoms=false

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push' && steps.tag_version.outputs.new_version
      with:
        tag
